# Generated by Django 2.2.1 on 2019-05-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Title of the article')),
                ('real', models.BooleanField(help_text='Whether or not the article is real (not from The Onion) or fake (from The Onion)')),
                ('correctlyGuessed', models.PositiveIntegerField(default=0)),
                ('incorrectlyGuessed', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
